# include:
#   - local: 'ci/install-docker-image.yml'
#   - local: 'ci/sf_deploy.yml'
#   - local: 'ci/sf_validate.yml'

stages:
  - docker
  - checkout
  - select_org
  - authenticate
  - generate_delta
  - scan
  - deploy
  - validate

before_script:
  - echo "Starting GitLab pipeline"

# Build and Push Docker Image
kaniko-build:
  stage: docker
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "Starting GitLab pipeline"
    - /kaniko/executor 
        --context $CI_PROJECT_DIR 
        --dockerfile $CI_PROJECT_DIR/Dockerfile 
        --no-push 
        --tar-path /tmp/my-app-image.tar



# Checkout source code
checkout_code:
  stage: checkout
  image: docker:latest
  services:
    - docker:dind
  script:
    - git fetch --unshallow || echo "Already shallow clone"
    - git checkout $CI_COMMIT_REF_NAME

# Selecting Target Org
select_target_org:
  stage: select_org
  image: docker:latest
  script:
    - cd $CI_PROJECT_DIR
    - echo "Selecting target org..."
    - chmod +x ./.gitlab/scripts/select_target_org.sh
    - ./.gitlab/scripts/select_target_org.sh "$CI_COMMIT_REF_NAME"
  artifacts:
    reports:
      dotenv: variables.env

authenticate_to_org:
  stage: authenticate
  image: docker:latest
  dependencies:
    - select_target_org
  script:
    - echo "Authenticating to Salesforce Org..."
    - chmod +x .gitlab/scripts/authenticate-to-org.sh
    - if [ ! -z "$ORG_ALIAS" ]; then
        ./.gitlab/scripts/authenticate-to-org.sh "$ORG_ALIAS" "auth_file.json";
      fi

# Create delta packages
generate_delta:
  stage: generate_delta
  image: docker:latest
  script:
    - ./.gitlab/actions/sf-generate-delta.sh "HEAD~1" "HEAD"

# Scan and Upload SARIF
scan_sarif:
  stage: scan
  image: docker:latest
  script:
    - ./.gitlab/actions/sf-code-scanner.sh || echo "Scan completed"

# Deploy Delta
deploy_delta:
  stage: deploy
  image: docker:latest
  dependencies:
    - authenticate_to_org
    - generate_delta
  script:
    - source variables.env
    - if [ ! -z "$ORG_ALIAS" ]; then
        ./.gitlab/actions/sf-deploy-delta.sh "$ORG_ALIAS";
      fi

# Validate Delta
validate_delta:
  stage: validate
  image: docker:latest
  dependencies:
    - authenticate_to_org
    - generate_delta
  script:
    - source variables.env
    - if [ ! -z "$ORG_ALIAS" ]; then
        ./.gitlab/actions/sf-validate-delta.sh "$ORG_ALIAS";
      fi

# Trigger only on Merge Requests to main, qa, or uat
# workflow:
#   rules:
    # - if: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /(main|qa|uat)/  
