stages:
  - auth

authenticate-to-org:
  stage: auth
  image: node:18
  variables:
    ORG_ALIAS: "my-org-alias"     # can be overridden in pipeline variables
    AUTH_FILE: "auth_file.json"   # can be overridden in pipeline variables
  script:
    - echo "Authenticating to Salesforce org..."
    - sf org login sfdx-url --sfdx-url-file "./$AUTH_FILE" --alias "$ORG_ALIAS"
    - echo "Authenticated to org with alias: $ORG_ALIAS"