stages:
  - select

select-target-org:
  stage: select
  image: alpine:latest
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'
    - if: '$CI_COMMIT_REF_NAME == "qa"'
    - if: '$CI_COMMIT_REF_NAME == "uat"'
  script:
    - chmod +x .gitlab/scripts/select_target_org.sh
    - ./.gitlab/scripts/select_target_org.sh "$CI_COMMIT_REF_NAME"
  artifacts:
    reports:
      dotenv: org_output.env
