stages:
  - select

select-target-org:
  stage: select
  image: alpine:latest
  variables:
    SF_AUTH_QA: ""
    SF_AUTH_UAT: ""
    SF_AUTH_PROD: ""
  script:
    - ./.gitlab/scripts/select_target_org.sh
  artifacts:
    reports:
      dotenv: org_output.env
