stages:
  - validate

check-deploy:
  stage: validate
  image: node:18   # or a custom image with Salesforce CLI pre-installed
  script:
    - echo "Running with API version 62"

    # Load TEST_CLASSES from previous stage
    - if [ -f build.env ]; then export $(cat build.env | xargs); fi

    # Validate delta package
    - |
      if [[ -d "changed-sources/force-app" ]]; then
        if [[ -z "$TEST_CLASSES" ]]; then
          echo "Validating without test classes..."
          sf project deploy start \
            --source-dir "changed-sources/force-app" \
            --dry-run \
            --target-org "$ORG_ALIAS" \
            --ignore-conflicts
        else
          echo "Validating with test classes: $TEST_CLASSES"
          sf project deploy start \
            --source-dir "changed-sources/force-app" \
            --dry-run \
            --target-org "$ORG_ALIAS" \
            --test-level "$TEST_LEVEL" \
            -t $TEST_CLASSES \
            --ignore-conflicts
        fi
      fi

      if [[ -d "changed-sources/destructiveChanges" ]]; then
        echo "Va
