stages:
  - checkout
  - select_org
  - authenticate
  - generate_delta
  - scan
  - deploy

variables:
  DOCKER_IMAGE: "$CI_REGISTRY_IMAGE/cloud-odyssey-docker-image-new:latest"

before_script:
  - echo "Starting GitLab pipeline"

# Checkout source code
checkout_code:
  stage: checkout
  image: docker:latest
  services:
    - docker:dind
  script:
    - git fetch --unshallow || echo "Already shallow clone"
    - git checkout $CI_COMMIT_REF_NAME

# Selecting Target Org
select_target_org:
  stage: select_org
  image: $DOCKER_IMAGE
  script:
    - echo "Selecting target org..."
    - ORG_ALIAS=$(./.gitlab/actions/select_target_org.sh "$SF_AUTH_QA")  # Assuming you have shell scripts for GitLab
    - echo "ORG_ALIAS=$ORG_ALIAS" >> variables.env
  artifacts:
    reports:
      dotenv: variables.env

# Authenticate to SF Org
authenticate_to_org:
  stage: authenticate
  image: $DOCKER_IMAGE
  dependencies:
    - select_target_org
  script:
    - source variables.env
    - if [ ! -z "$ORG_ALIAS" ]; then
        ./.gitlab/actions/authenticate-to-org.sh "$ORG_ALIAS" "auth_file.json";
      fi

# Create delta packages
generate_delta:
  stage: generate_delta
  image: $DOCKER_IMAGE
  script:
    - ./.gitlab/actions/sf-generate-delta.sh "HEAD~1" "HEAD"

# Scan and Upload SARIF
scan_sarif:
  stage: scan
  image: $DOCKER_IMAGE
  script:
    - ./.gitlab/actions/sf-code-scanner.sh || echo "Scan completed"

# Deploy Delta
deploy_delta:
  stage: deploy
  image: $DOCKER_IMAGE
  dependencies:
    - authenticate_to_org
    - generate_delta
  script:
    - source variables.env
    - if [ ! -z "$ORG_ALIAS" ]; then
        ./.gitlab/actions/sf-deploy-delta.sh "$ORG_ALIAS";
      fi

